# Generated by Django 4.2.3 on 2023-07-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiales',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='trabajos',
            name='idCliente',
        ),
        migrations.RemoveField(
            model_name='trabajos',
            name='idListMat',
        ),
        migrations.RemoveField(
            model_name='trabajos',
            name='idObra',
        ),
        migrations.RemoveField(
            model_name='trabajos',
            name='idUsuario',
        ),
        migrations.RemoveField(
            model_name='trabmat',
            name='idFamilia',
        ),
        migrations.RemoveField(
            model_name='trabmat',
            name='idMat',
        ),
        migrations.RemoveField(
            model_name='trabmat',
            name='idTrabajo',
        ),
        migrations.RemoveField(
            model_name='trabmat',
            name='idUsuario',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Materiales',
        ),
        migrations.DeleteModel(
            name='MaterialesF',
        ),
        migrations.DeleteModel(
            name='Obras',
        ),
        migrations.DeleteModel(
            name='Trabajos',
        ),
        migrations.DeleteModel(
            name='TrabMat',
        ),
    ]
