# Generated by Django 4.2.3 on 2023-07-10 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminv', '0004_remove_materiales_nombre_remove_obras_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=254)),
                ('tel1', models.CharField(max_length=20)),
                ('tel2', models.CharField(blank=True, max_length=20)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'app_Clientes',
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_Materiales',
            },
        ),
        migrations.CreateModel(
            name='MaterialesF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descrip', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_Familias',
            },
        ),
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir', models.CharField(max_length=100)),
                ('notas', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminv.clientes')),
            ],
            options={
                'db_table': 'app_Obras',
            },
        ),
        migrations.CreateModel(
            name='Trabajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.TimeField()),
                ('notas', models.CharField(max_length=200)),
                ('created_at', models.BooleanField()),
                ('idCliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminv.clientes')),
                ('idListMat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminv.materiales')),
                ('idObra', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminv.obras')),
                ('idUsuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_Trabajos',
            },
        ),
        migrations.CreateModel(
            name='TrabMat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.BooleanField()),
                ('idFamilia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminv.materialesf')),
                ('idMat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminv.materiales')),
                ('idTrabajo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminv.trabajos')),
                ('idUsuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_TrabMat',
            },
        ),
        migrations.AddField(
            model_name='materiales',
            name='nombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminv.materialesf'),
        ),
    ]
