# Generated by Django 4.2.3 on 2023-07-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminv', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabmat',
            name='idFamilia',
        ),
        migrations.RemoveField(
            model_name='trabmat',
            name='idMat',
        ),
        migrations.RemoveField(
            model_name='trabmat',
            name='idTrabajo',
        ),
        migrations.RemoveField(
            model_name='trabmat',
            name='idUsuario',
        ),
        migrations.AlterModelTable(
            name='materialesf',
            table='app_MaterialesF',
        ),
        migrations.DeleteModel(
            name='Trabajos',
        ),
        migrations.DeleteModel(
            name='TrabMat',
        ),
    ]
