# Generated by Django 4.2.3 on 2023-07-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminv', '0006_remove_trabmat_idfamilia_remove_trabmat_idmat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminv.materialesf'),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
