# Generated by Django 4.2.3 on 2023-07-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminv', '0008_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horas',
            name='horaSal',
            field=models.TimeField(null=True),
        ),
    ]
